--- #YAML:1.0
name:               Data-BitStream
version:            0.02
abstract:           A class implementing a stream of bits and coding methods
author:
    - Dana A Jacobsen <dana@acm.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mouse:        0.58
    Mouse::Role:  0.58
    Test::More:   0.82
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
