---
abstract: 'A class implementing a stream of bits and coding methods'
author:
  - 'Dana A Jacobsen <dana@acm.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6101, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-BitStream
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.57
  Mouse: 0.58
  Mouse::Role: 0.58
  Test::More: 0.94
version: 0.04
